name: CD
on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest
    name: CD
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          SCRIPT_BEFORE: |
            whoami
            ls -al