name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: add known hosts
      run: ssh-keyscan -p 35222 -H 170.231.15.86 >> ~/.ssh/known_hosts
      
    - name: connect ssh 
      run: |
        ssh ubuntu@170.231.15.86 -p 35222 