name: cicd

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Set Docker Image Tag
      id: tag
      run: |
        if [[ $GITHUB_REF == refs/heads/main ]]; then
          echo "::set-output name=TAG::latest"
        elif [[ $GITHUB_REF == refs/heads/dev ]]; then
          echo "::set-output name=TAG::dev"
        else
          echo "::set-output name=TAG::unknown"
        fi

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.tag.outputs.TAG }}
        labels: ${{ steps.tag.outputs.TAG }}

  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: Build

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy remote server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker run -it -d -p 8088:8088 --name qualitor-api \
            -e FLASK_RUN_HOST=8088 \
            -e QUALITOR_DB_HOST='10.40.76.3' \
            -e QUALITOR_DB_USR='sa' \
            -e QUALITOR_DB_PWD='54exXKmbohXPaoBdauCqEkEA4MjAUZO9' \
            -e QUALITOR_DB_BASE='QUALITOR_PROD' \
            -e QUALITOR_URI='https://qltapi.vantix.com.br/qualitor/ws/services/service.php?wsdl=' \
            -e QUALITOR_WS_USR='ws.vantix' \
            -e QUALITOR_WS_PWD='qlt@1!@#' \
            -e TZ=America/Sao_Paulo \
            -v /etc/hosts:/etc/hosts \
            prcamargo/qualitor-api