name: Deployment Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy no srv
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.HOST_PORT }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PWD }}          
          script: |
             sudo su
             mkdir /tmp/teste