name: CD
on: [push]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 170.231.15.86
          username: ubuntu
          password: 11
          port: 35222
          script: |
            ls